# schema registry 8081
apiVersion: v1
kind: Service
metadata:
  name: mykafka-cp-schema-registry-lb
spec:
  ports:
  - name: schema-registry
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: cp-schema-registry
    release: mykafka
  type: LoadBalancer
---
# kafka 9092 + 42090
apiVersion: v1
kind: Service
metadata:
  name: mykafka-cp-kafka-lb-42092
spec:
  ports:
  - name: broker
    port: 42092
    protocol: TCP
    targetPort: 9092
  selector:
    app: cp-kafka
    release: mykafka
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mykafka-cp-kafka-lb-9092
spec:
  ports:
  - name: broker
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: cp-kafka
    release: mykafka
  type: LoadBalancer
---
# control center 9021
apiVersion: v1
kind: Service
metadata:
  name: mykafka-cp-control-center-lb
spec:
  ports:
  - name: cc-http
    port: 9021
    protocol: TCP
    targetPort: 9021
  selector:
    app: cp-control-center
    release: mykafka
  type: LoadBalancer
---
# kafka-connect 8083
apiVersion: v1
kind: Service
metadata:
  name: mykafka-cp-kafka-connect-lb
spec:
  ports:
  - name: kafka-connect
    port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: cp-kafka-connect
    release: mykafka
  type: LoadBalancer
---
# ksql 8088
apiVersion: v1
kind: Service
metadata:
  name: mykafka-cp-ksql-server-lb
spec:
  ports:
  - name: ksql-server
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: cp-ksql-server
    release: mykafka
  type: LoadBalancer
---


