// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratedSchemas
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class MotionEvent1 : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"MotionEvent1\",\"namespace\":\"GeneratedSchemas\",\"fields\":[{" +
				"\"name\":\"id\",\"type\":\"int\"},{\"name\":\"eventtimestamp\",\"type\":{\"type\":\"long\",\"logica" +
				"lType\":\"timestamp-millis\"}},{\"name\":\"camera\",\"type\":\"string\"}]}");
		private int _id;
		private System.DateTime _eventtimestamp;
		private string _camera;
		public virtual Schema Schema
		{
			get
			{
				return MotionEvent1._SCHEMA;
			}
		}
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		public System.DateTime eventtimestamp
		{
			get
			{
				return this._eventtimestamp;
			}
			set
			{
				this._eventtimestamp = value;
			}
		}
		public string camera
		{
			get
			{
				return this._camera;
			}
			set
			{
				this._camera = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.id;
			case 1: return this.eventtimestamp;
			case 2: return this.camera;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.id = (System.Int32)fieldValue; break;
			case 1: this.eventtimestamp = (System.DateTime)fieldValue; break;
			case 2: this.camera = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
